Controllers/TweetController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Jetweet.Data;
using Jetweet.Models;

namespace Jetweet.Controllers {
  public class TweetController : Controller {
    private readonly ApplicationDbContext _context;

    public TweetController (ApplicationDbContext context) {
      _context = context;
    }

    // GET: Tweet
    public async Task<IActionResult> Index () {
      if (User.Identity.IsAuthenticated) {
        return View (await _context.Tweet.OrderByDescending (d => d.Id).ToListAsync ());
      } else {
        return Redirect ("/Identity/Account/Login");
      }
    }

    // GET: Tweet/Details/5
    public async Task<IActionResult> Details (int? id) {
      if (id == null) {
        return NotFound ();
      }

      var Tweet = await _context.Tweet
        .FirstOrDefaultAsync (m => m.Id == id);
      if (Tweet == null) {
        return NotFound ();
      }

      return View (Tweet);
    }

    // GET: Tweet/Create
    public IActionResult Create () {
      if (User.Identity.IsAuthenticated) {
        return View ();
      } else {
        return RedirectToAction (actionName: "Index");
      }
    }

    // POST: Tweet/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create ([Bind ("Id,Text,ImageUrl")] Tweet Tweet) {
      if (ModelState.IsValid) {
        _context.Add (Tweet);
        await _context.SaveChangesAsync ();
        return RedirectToAction (nameof (Index));
      }

      return View (Tweet);
    }

    // GET: Tweet/Edit/5
    public async Task<IActionResult> Edit (int? id) {
      if (id == null) {
        return NotFound ();
      }

      var Tweet = await _context.Tweet.FindAsync (id);
      if (Tweet == null) {
        return NotFound ();
      }

      return View (Tweet);
    }

    // POST: Tweet/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit (int id, [Bind ("Id,Text,ImageUrl")] Tweet Tweet) {
      if (id != Tweet.Id) {
        return NotFound ();
      }

      if (ModelState.IsValid) {
        try {
          _context.Update (Tweet);
          await _context.SaveChangesAsync ();
        } catch (DbUpdateConcurrencyException) {
          if (!TweetExists (Tweet.Id)) {
            return NotFound ();
          } else {
            throw;
          }
        }

        return RedirectToAction (nameof (Index));
      }

      return View (Tweet);
    }

    // GET: Tweet/Delete/5
    public async Task<IActionResult> Delete (int? id) {
      if (id == null) {
        return NotFound ();
      }

      var Tweet = await _context.Tweet
        .FirstOrDefaultAsync (m => m.Id == id);
      if (Tweet == null) {
        return NotFound ();
      }

      return View (Tweet);
    }

    // POST: Tweet/Delete/5
    [HttpPost, ActionName ("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed (int id) {
      var Tweet = await _context.Tweet.FindAsync (id);
      _context.Tweet.Remove (Tweet);
      await _context.SaveChangesAsync ();
      return RedirectToAction (nameof (Index));
    }

    private bool TweetExists (int id) {
      return _context.Tweet.Any (e => e.Id == id);
    }

    [ResponseCache (Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error () {
      return View (new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    public IActionResult Privacy () {
      return View ();
    }
  }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>@ViewData["Title"] - Jetweet</title>

  <environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css"/>
  </environment>
  <environment exclude="Development">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
  </environment>
</head>
<body>
<header>
  <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-blue border-bottom box-shadow mb-3">
    <div class="container">
      <a class="navbar-brand" href="~/">
        <i class="fa fa-twitter" aria-hidden="true"></i>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
        <partial name="_LoginPartial"/>
      </div>
    </div>
  </nav>
</header>
<div class="container">
  <partial name="_CookieConsentPartial"/>
  <main style="margin-left:auto;margin-right:auto;" role="main" class="containor">
    @RenderBody()
  </main>
</div>

<footer class="border-top footer pl-3 text-muted">
  <div class="container">
    &copy; 2018 - Jetweet - <a asp-area="" asp-controller="Tweet" asp-action="Privacy">Privacy</a>
  </div>
</footer>

<environment include="Development">
  <script src="~/lib/jquery/dist/jquery.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
          asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
          asp-fallback-test="window.jQuery"
          crossorigin="anonymous"
          integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
          asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
          asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
          crossorigin="anonymous"
          integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
  </script>
  <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("Scripts", required: false)
</body>
</html>